---
ip: "192.168.56.56"
memory: 4096
cpus: 4
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: ~/workspace
      to: /home/vagrant/code
    - map: ~/compartida
      to: /home/vagrant/compartida

sites:
    - map: grecia.local
      to: /home/vagrant/code/grecia/public
      php: "7.2"
    - map: phpmyadmin.local
      to: /home/vagrant/code/phpmyadmin

databases:
    - grecia

features:
    - mysql: true
    - mariadb: false
    - postgresql: false
    - ohmyzsh: true
    - webdriver: true

services:
    - enabled:
          - "mysql"
#    - disabled:
#        - "postgresql@11-main"

#ports:
#    - send: 33060 # MySQL/MariaDB
#      to: 3306
#    - send: 4040
#      to: 4040
#    - send: 54320 # PostgreSQL
#      to: 5432
#    - send: 8025 # Mailhog
#      to: 8025
#    - send: 9600
#      to: 9600
#    - send: 27017
#      to: 27017
